function [] = myformat(gca)
%% Plots not with respect to time

set(gca,...
  'Box'         , 'on'      , ...
  'FontName'    , 'AvantGarde', ...
  'FontSize'    , 10         , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.015 .015] , ...
  'YMinorTick'  , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XGrid'       , 'on'      , ... 
  'YGrid'       , 'on'      , ... 
  'LineWidth'   , 1         );

end

