function [axplot]  = myplot( t,var_plot,spacer )

% Test if the var plot is a cell or not.  This is used because when
% plotting 2 or more plots on one graph they both must be a cell.
if iscell(var_plot)   
else
    var_plot = {var_plot};
end


days = floor(t(end)+1)-floor(t(1));

ax(1) = gca;

xData_hour = linspace(floor(t(1)),floor(t(end)+1),days*2/60+1);
yData      = -200:spacer:-200 ;
set(ax(1),...  
  'XAxisLocation','bot'      ,...
  'YAxisLocation','right'     ,...
  'Box'         , 'on'      , ...
  'FontName'    , 'AvantGarde', ...
  'FontSize'    , 10         , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.015 .015] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XTick'       , xData_hour, ...
  'YTick'       , yData, ...
  'LineWidth'   , 1         );
 datetick('x','HH','keepticks');
xlabel('Hour','FontName', 'Avant Garde');


xData_day = linspace(floor(t(1)),floor(t(end)+1),days/60+1);
ax(2) = axes('Position',get(ax(1),'Position'),...
  'XAxisLocation','top'      ,...
  'YAxisLocation','left'     ,...
  'Box'         , 'on'      , ...
  'FontName'    , 'AvantGarde', ...
  'FontSize'    , 10         , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.015 .015] , ...
  'YMinorTick'  , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XTick'       , xData_day     , ...
  'YTick'       , -40:spacer:40    , ...
  'XAxisLocation','top'      ,...
  'XGrid'       , 'on'      , ...
  'LineWidth'   , 1         );
 datetick('x','dd-mmm (DDD)','keepticks');


% This is the only way I could find to plot this way
hold on

for i=1:length(var_plot)
 axplot(i) = plot(t,var_plot{i},'LineWidth',1);
end
 
hold off 

end

